### ISSUE TITLE
Analyzation error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ikabirov** [JSMonk/hegel#101]
```js
const map = new WeakMap()
map.has({})
```

**Comment by srg-kostyrko** [comment]
I tried debugging this issue
this seems to be a problem with generics refinement in `new` calls

here is a bare sample that produces the same error 

http://localhost:3000/try/#MYGwhgzhAEAqCmEAuAeWA+aBvAsAKGkOmAHsA7ZAJwFdgkTKAKASmwF98O99SKlp+AXmhl4AdziIkLQkA

if the generic type is not specified in new call - getRawFunction returns $BottomType that cannot be unpacked (it is still $BottomType after the call)

this requires a deep understanding of generics and $BottomType to solve - this is beyond my skills for now :(

**Comment by JSMonk** [comment]
Oh, okay. The solving of the problem with `$BottomType` will solve a lot of issues. So, I currently try to fix it in the context of #133
