### ISSUE TITLE
High order function type inheritance

### ISSUE THREAD

**Issue by nanot1m** [JSMonk/hegel#104]
If we declare two functions:
```js
const id = x => x
const K = a => b => a
```

And then pass `id` as the argument to `K`
```js
const second = K(id)
```
Type of the function `second` will be `<_c, _a>(_c) => _a`,
but it should be something like `<_c>(_c) => <_b>(_b) => _b`

https://jsmonk.github.io/hegel/try#MYewdgzgLgBAlgExgXhgDxQPnQKFJWAM2hRgEMsYAjSsvcEiMJVYqACkQEp6CYwArgFsAXDACMpNu3Fd2AcnHye+RlABOY+QCZ5pJghlydynEA

**Comment by JSMonk** [comment]
Good issue. We will fix it soon.
Thank you for your contribution ^_^

**Comment by nanot1m** [comment]
It is working now!

**Comment by JSMonk** [comment]
Seems like it not :C

**Comment by nanot1m** [comment]
I don't see any issues on https://hegel.js.org/try
