### ISSUE TITLE
Move site to hegel.js.org which is more professional looking

### ISSUE THREAD

**Issue by sirinath** [JSMonk/hegel#109]
Maybe you can move to hegel.js.org using https://js.org/

Also maybe this project can be moved to own GitHub organisation so it becomes more than and individual project.

**Comment by JSMonk** [comment]
Oh. It's a cool idea. Thank you a lot ^_^.

**Comment by JSMonk** [comment]
Documentation was moved to https://hegel.js.org/
Thank you one more time :3
