### ISSUE TITLE
Rest arguments don't work with generics

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#113]
https://jsmonk.github.io/hegel/try#GYVwdgxgLglg9mABAQwDwBUB8AKAdPmKAUwFsBnALkQEEAnW5ATw0wEpEBvAKEUVqKghaSQqTIBuLgF8gA

it reports `Rest argument type should be an array-like` error

**Comment by JSMonk** [comment]
Hmmm. It's a hard bug. We will fix it soon. Thank you for your contribution ^_^.
