### ISSUE TITLE
Type produced by $Partial is soft even if initial type isn't 

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#116]
https://jsmonk.github.io/hegel/try#C4TwDgpgBAqgzhATlAvFA3gKClAdgQwFsIAuKOYRAS1wHMAabKfW0vAV0ICMlGBfANyYAZu1wBjYFQD2uKGHzBxACwAU06rRr4ANmXi8o7MABNFEOGQAkABXyIpugDwHEAPgCU+hMiw5EEMDsiHJ+OHhEbMZmwBYAdATEUAA+yVAaVFoEOgmRjOHMrGTR5nBxLNCp6ZraORVMgph8mOKyFNWZtd5IqBgRxGQARBlZuv0Qg-SFbABMAAxQja247dI6JkiuvQpKaiO1U+jkVABeszOLHgJQAPQ3UBAAHpCSD4iIGlDKSBBAA

I would expect $Partial to be strict if the initial type was strict

**Comment by JSMonk** [comment]
Oh yes. It seems like Hegel returns Soft Object type. We will fix it soon.
Thank you for your contribution ^_^.
