### ISSUE TITLE
Differences/advantages over TS

### ISSUE THREAD

**Issue by dzek69** [JSMonk/hegel#131]
Hello,

I usually like alternative-to-mainstream solutions, but what I always look for in README for differences or advantages of alternative solution over popular solutions.

Can we have something like that in README? If that's already in docs (which is down right now, no DNS record for hegel.js.org) then just linking that from README would be useful.

Thanks

Edit: To clarify - I don't really know TS. I'm at point of looking around and choosing right solution for me. I see some differences in those examples in README, but when I don't already know other solution I cannot really decide which is better for me.

**Comment by JSMonk** [comment]
Oh. It's a good point. Thank you. I will add it into README.
Thank you a lot for your contribution ^_^.

**Comment by thecotne** [comment]
@dzek69 i am working on creating article about flow vs ts vs hegel here is [working draft](https://github.com/thecotne/state-of-js-type-systems)

also there is [Why Hegel?](https://hegel.js.org/docs#why-hegel) section on website that can be linked in readme or contents of it can be copied over to readme ...
