### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by lhorie** [JSMonk/hegel#132]
Repro steps: 
1) in Chrome, go to https://hegel.js.org/
2) click "docs" in top right corner

Expected: docs page (https://hegel.js.org/docs/)
Actual: not found (https://hegel.js.org/hegel/docs)

This issue affects links all over the docs site

**Comment by JSMonk** [comment]
Oh. Sorry, it will be fixed after a few minutes. Thank you for contribution ^_^.

**Comment by JSMonk** [comment]
Fixed :3

**Comment by lhorie** [comment]
👍 Thanks for the fast response
