### ISSUE TITLE
Plugin system to support new ES syntax?

### ISSUE THREAD

**Issue by linonetwo** [JSMonk/hegel#134]
When using flow, lack of new syntax support is a pain.
https://github.com/facebook/flow/labels/ES2015%2B

Will hegel support plugin system or reuse babel transforms? So it can support some new syntax from community plugin, instead of letting users waiting for core support for a long time?

**Comment by JSMonk** [comment]
Hi. Hegel uses Babel as a parser, but doesn't compile your code, but, Hegel needs to inference the result of an invocation of new operators, so we will try to provide analysis for any new syntax.
Thank you for contribution ^_^

**Comment by linonetwo** [comment]
Glad to hear that! Flow lacks optional chaining for a really long time... It just ignores that useful syntax.

I will close this issue since this is just a question, not a real big issue.
