### ISSUE TITLE
$Partial converts soft type into strict

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#135]
https://hegel.js.org/try#C4TwDgpgBAqgzhATlAvFA3gKClAdgQwFsIAuKOYRAS1wHMAabKfW0vAV0ICMlGcA6QZgC+AbkwAzdrgDGwKgHtcUMPmAyAFgAoF1WjXwAbMvF5R2YACZqIcMgBIACvkTyjAHlOIAfAEoTCMhYOIgQwOyIysE4eERsFtbAtvwExFAAPulQulT6BIYpcXwxLPFWNnD8pRlZOXlGVaxMYiKYMkoU2XoGxrCBqBixxGQARHU9QxAj9MysZABMAAwzcFQAXmzzUC3tuJ0KhpZIXgOq6trj+TPo5OubW8K+olAA9C94ClBIiLpQGkgQIA

**Comment by JSMonk** [comment]
Thank you for contribution ^_^
