### ISSUE TITLE
Tooltips in playground isn't work in firefox

### ISSUE THREAD

**Issue by Demetri0** [JSMonk/hegel#136]
Tooltips in playground isn't work in firefox (tested on latest version 75.0)
No errors in console.

https://hegel.js.org/try

**Comment by artlaman** [comment]
Thats probably because safari and firefox [do not have support](https://caniuse.com/#feat=js-regexp-lookbehind) for lookbehind regexes yet.
https://github.com/JSMonk/hegel/blob/92e54ff8d62aaf7d64e309a8d7f1b4fcff5e751f/packages/core/src/type-graph/types/type.js#L124-L127

**Comment by JSMonk** [comment]
Oh, okay. I will try to fix it today.

**Comment by JSMonk** [comment]
Thank you for contribution ^_^
