### ISSUE TITLE
disallow non strict comparison

### ISSUE THREAD

**Issue by thecotne** [JSMonk/hegel#145]
disallow non strict comparison as it implies implicit type conversion (which i think should not be allowed in sound type system)

**Comment by JSMonk** [comment]
It's a nice idea. I will think about a soft implementation of the proposal. 
Thank you for your contribution ^_^

**Comment by vkurchatkin** [comment]
> which i think should not be allowed in sound type system)

This has nothing to do with soundness. == is perfectly safe and even sometimes useful.

**Comment by thecotne** [comment]
@vkurchatkin you are right about soundness.

but i am curious what is a use case for `==` since i am developing with [eslint/eqeqeq](https://eslint.org/docs/rules/eqeqeq) for at past least 3 years.

this issue probably can be closed since eslint has this feature and there is no point in optional support in hegel since if someone wanted to opt in for this there is eslint/eqeqeq...
