### ISSUE TITLE
Add cache to doc build workflow

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#159]
On the latest stream, you mentioned that docs build on CI takes lots of time.
For sure gatsby build is slow but I'm pretty sure this is partially due to installing dependencies
I suggest adding caching for dependencies - this way it will not reinstall them unless there were new packages installed

here is an example of such config
https://github.com/actions/cache/blob/master/examples.md#node---npm

**Comment by JSMonk** [comment]
Oh, it's really nice. Could you make PR with the changes inside [`Docs Deployment`](https://github.com/JSMonk/hegel/blob/master/.github/workflows/deploy-docs.yml)?
