### ISSUE TITLE
Problem with for loop

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#162]
if checking for equality there is an error `Variable "i" is not defined!` in testing part of for loop

https://hegel.js.org/try#GYewTgBAFANgpgFwgSwgXggRgAwG4UQB8EeKAtGQJQQDeAvhAPSMQDG4YcrSAdiBHDBhwEABaC4AKEmhIsRAQw58qNGqy5kFavSYsA7sJ4BzCADUAhmGQWARvAgAiZI5QBnCHyQATOMGQ8cN4AhAJC4EA

**Comment by JSMonk** [comment]
Hah. It's weird. We will fix it soon. Thank you for the contribution ^_^.
