### ISSUE TITLE
Issue with type refinement when union of primitive types is unboxed 

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#171]
https://hegel.js.org/try#GYVwdgxgLglg9mABAJwKYAdUEMoAopbIDmqUAXIgM5TIxhGIA+iYIAtgEarIA0isbVJQqtO3AJQVqtekxbsuyRAG8AUIkQxgifAE9McbQWKlEAXguIARKMVXxK9RpSkQyJMZJREAKh-8YQUoAbicAXyc0KDcPQi8AOjRMHHxAoXFQsMRVVQB6XMQAUWRkOGQKABV9VGtgLAAbSlQrTUpNSDg2dBwYDnqagHcYKAALfmrrW245aToiK1Uk7Dw6xtQ+ABYM1SA

The issue is discovered on the latest version in `master` - hegel.js.org running `0.0.40` is fine

**Comment by JSMonk** [comment]
Okay. We will try to understand the problem in the snippet.
