### ISSUE TITLE
Object optional properties not working

### ISSUE THREAD

**Issue by srg-kostyrko** [JSMonk/hegel#172]
https://hegel.js.org/try#MYewdgzgLgBArhApgJwFwwN40QWwIYCWANutMgWAOYA0MADnhBAO4jIAm6A-GRZTAF8YAXkwwweHInQAiPGACeAOgQoAApXzEloHDMEBuGAHpjMQLwbgGR2AhACggA

**Comment by JSMonk** [comment]
It's a non-valid example because in type we annotated name and in the object we provide an email.
https://hegel.js.org/try#MYewdgzgLgBArhApgJwFwwN40QWwIYCWANutMgWAOYA0MADnhBAO4jIAm6A-GRZTAF8YAXkzZ8xdACI8YAJ4A6BCgAClCUQWgcUwQG4YAekMxAvBuAZHYCEAKCA

**Comment by srg-kostyrko** [comment]
yeh, sorry - this is example from docs, will update it
