### ISSUE TITLE
Type "boolean" is incompatible with type "false | true"

### ISSUE THREAD

**Issue by thecotne** [JSMonk/hegel#177]
```js
function foo(a: true | false): undefined {
    
}
function bar(): boolean {
    return true
}

foo(bar()) //Err Type "boolean" is incompatible with type "false | true"
```

[try](https://hegel.js.org/try#GYVwdgxgLglg9mABMOcAUBDAXIqAnEAU0QB9kMAbAZ0IEodwATQ4GMQxxAbwChF-EPAL49QkWAkQAjDHjT1pqCoQxJeAxHkJQQeJPiLCeo1GhlzatIA)

**Comment by JSMonk** [comment]
Thank you for reporting. It's already fixed, so, it will be added in the next version. Please, don't close the issue. I will close it by myself after the new version will be published.

Thank you for your contribution ^_^.
