### ISSUE TITLE
Objects to unions converter

### ISSUE THREAD

**Issue by vasilii-kovalev** [JSMonk/hegel#184]
Let's say we have a dictionary:
```javascript
const FEATURES = {
  SORTING: 'Sorting',
  FILTERING: 'Filtering',
  REORDERING: 'Reordering',
};
```

It can be used like this:
```javascript
const features = [];

// or it can be a method of a class like "addFeature"
features.push(FEATURES.FILTERING);
```

I want to say to my `features` array that it can accept values of the `FEATURES` object only. But in order to avoid creating a separate union type and support (possible) changes there and in FEATURES object, I'd like to collect values from the object and keep them as a union type. Thus if it is necessary to add/remove value, it can be done in only one place - in the `FEATURES` object.

To achieve this goal, in TypeScript it is necessary to define such monstrous type:
```javascript
const FEATURES = {
  SORTING: 'Sorting',
  FILTERING: 'Filtering',
  REORDERING: 'Reordering',
// 1. const assertions
} as const;

// 2. if we have a lot of such dictionaries, we have to repeat this stuff every time
type Feature = (typeof FEATURES)[keyof typeof FEATURES];

// if we want to get union type of keys
// type FeatureKeys = keyof typeof FEATURES;

const features: Feature[] = [];

// OK
features.push(FEATURES.FILTERING);

/*
  Should throw a type error
  Argument of type '"foo"' is not assignable to parameter of type
  '"Sorting" | "Filtering" | "Reordering"'.
*/
features.push('foo')
```

Are there any thoughts of optimizing this type generation to avoid repeating such boilerplate in Hegel? Like a help function or something.

And I'd like to know if it is a common thing to work with dictionaries this way or not. Because I'm new to strong type checking and maybe I think the wrong way here...

Thanks in advance.

**Comment by thecotne** [comment]
- `Object.freeze` function will do what `as const` does
- `$TypeOf` magic type will do what `typeof` does 
- `$Keys` magic type does what `keyof` does but if you want values `$Values` magic type will do that

```js
const FEATURES = Object.freeze({
  SORTING: 'Sorting',
  FILTERING: 'Filtering',
  REORDERING: 'Reordering'
})

type Feature = $Values<$TypeOf<FEATURES>>

const features: Array<Feature> = []

void features.push('Filtering') // ok
void features.push(FEATURES.FILTERING) // ok

void features.push('foo') // error as expected
```

[try](https://hegel.js.org/try#MYewdgzgLgBAYgUQIIBUCqAlBBlGBeGAeQCMArAU2CgDoAzAJ3PIC9yAKAbwCgYZtCMKAJIA5AOIAuGAHJsIelACWYAObSAND3hCAMigQZRkmXEUAbKOXrK1m3lgEARA0anSM5eQBMrN6VwBfAEouLigATwAHcnhyAEMoAFdGfBgAEgA1OLNE8ggAHjSUKPJCWnzEVEwcAD4a0NBIWFp4pMYIKSR6ejjwitbk8hrUgG0AXVCANxBFLxgWhMGIakjEiAALNmlTC19VaSCYAHojmBAAay5p2fmB9pW1zcr0LGxqOF19Q3FDk7PLq4zOYLNp5B4bLa0EAgA7HU5WejyGBxCAwcgAD2iVHIXiAA)


only down side would be that `FEATURES` will be frozen on runtime as well (this may or may not be desired behavior)

**Comment by thecotne** [comment]
if you don't like to freeze object on runtime you can create helper `immutableId` function that will refine type but don't change value for runtime

```js
const immutableId = <T>(v: T): $Immutable<T> => v

const FEATURES = immutableId({
  SORTING: 'Sorting',
  FILTERING: 'Filtering',
  REORDERING: 'Reordering'
})
```

**Comment by vasilii-kovalev** [comment]
@thecotne, thanks for your examples. It makes the code a little bit easier, but the problem actually in `Feature` type definition repetition. I tried to apply `immutableId` approach to `Feature`, but failed of course :)

I tried to get something like this:
```javascript
// without output type because have no ideas how to describe it
const makeUnion = (obj: object) => $Values<$TypeOf<obj>>;

type Feature = makeUnion(FEATURES);
```
but it seems that type definition doesn't work this way :)

**Comment by thecotne** [comment]
this works perfectly fine you don't need to repeat anything ...

```js
const immutableId = <T>(v: T): $Immutable<T> => v

const FEATURES = immutableId({
  SORTING: 'Sorting',
  FILTERING: 'Filtering',
  REORDERING: 'Reordering'
})

type Feature = $Values<$TypeOf<FEATURES>>

const features: Array<Feature> = []

void features.push('Filtering') // ok
void features.push(FEATURES.FILTERING) // ok

void features.push('foo') // error as expected
```

[try](https://hegel.js.org/try#MYewdgzgLgBAlgWwQVygQwEYBsCmBJAExgF4YAeAFQD4AKANwC4YKBKJgEjyVU10qpIC6AKGGhIsAGIBRAIIUAqgCVpAZRLxu6bPgI0A3sJgxVAeSUU8AOQDiTAOSqQAJyhwwAc3sAaIzEl4ADIU0krWdjD2knBYUDjO7l6+xirmACKh4Q5KOC4E8Yn2wgC+LKJQAJ4ADjj+OGhQyM61pOwAamhYyDgQZOwU1TimAGZkMvLKalRUouLQMMP1jc0QTLLOzmgVY0tNOAKkANoAuqJ0IHBEiw17EAB0VcgQABY0UTFxCZ72LDAA9H8YCAANbCc6XBa7FYPJ6vcaKFSqO4BYKZWy-AFA0Fgi5XKE9GEvN7DEAgH7-QHxZwuGBoCAwHAADxqwDiBCAA)

you just need to use either `Object.freeze` or `immutableId` to achieve same result as `as const` in typescript.

**Comment by thecotne** [comment]
@vasilii-kovalev i have reported `Values` type issue separately https://github.com/JSMonk/hegel/issues/269
