### ISSUE TITLE
Incorrect type compatibility of JS data types

### ISSUE THREAD

**Issue by leushkin** [JSMonk/hegel#187]
https://hegel.js.org/try#MYewdgzgLgBAZiEMC8NoCcUD41XQOihAFUAHUgU3QGEBDCCgCgEoAoVhERgcgAsKANgJDdmQA

I agree with a type of foo function, but when I try to apply string to this function Hegel returns an error. Hegel should consider string | number | ... also as objects with methods

**Comment by thecotne** [comment]
duplicate of https://github.com/JSMonk/hegel/issues/126

**Comment by JSMonk** [comment]
Thank you for your contribution ^_^. I will fix it with #126.
