### ISSUE TITLE
Type "[T]" is incompatible with type "Array<T>"

### ISSUE THREAD

**Issue by thecotne** [JSMonk/hegel#199]
```ts
function ensureArray<T>(value: T | Array<T> | null | undefined): Array<T> {
  if (value == null) {
    return []
  }

  if (typeof value === 'object' && value instanceof Array) {
    return value
  } else {
    return [value]// Type "[T]" is incompatible with type "Array<T>"
  }
}
```

[try](https://hegel.js.org/try#GYVwdgxgLglg9mABAUzAZxAJ2QQU5gQwE8AeAFQD4AKANwIBsRkAuRMxAH0T0NMs8RgQ9egPAATZMBhhk4gJSsexchUQBvAFCJEMYIloMmiALwnBw+vI3adibFCxIA2gF1bAX0229BqEQAHZDh9OkZkUzNEAHI4ACMAK2RoaMQAMjTEMOMZNCgCSGD9ZSJrLTt7ZEdMJGzkTxR6NAjyuwcnRGc69x0vDyA)

**Comment by thecotne** [comment]
surprisingly (for me) this works

```js
function ensureArray<T>(value: T): Array<T> {  
  return [value]
}
```

[try](https://hegel.js.org/try#GYVwdgxgLglg9mABAUzAZxAJ2QQU5gQwE8AeAFQD4AKANwIBsRkAuRMgSlb0NMsQG9EiAFBDsULEgDadRsgC6wgL5A)

**Comment by ikabirov** [comment]
Hmmm
```js
function ensureArray<T>(value: T | Array<T> | null | undefined): Array<T> {
  if (value == null) {
    return []
  }

  if (value instanceof Array) {
    return value
  } else {
    value
    return [value]
  }
}
```
[try](https://hegel.js.org/try#GYVwdgxgLglg9mABAUzAZxAJ2QQU5gQwE8AeAFQD4AKANwIBsRkAuRMxAH0T0NMs8RgQ9egPAATZMBhhk4gJSsexchUQBvAFCJEMYIloMmiALwnBw+vI3adibFCxIA2gF1bAX0229Buo2RddCgCSGQ4fWUiay07e2RHTCR-Jk8UejRA2LsU5FsdBydEZ1z3HS8PIA)
