### ISSUE TITLE
Type "(string) => string" is incompatible with type "<T>(T) => T"

### ISSUE THREAD

**Issue by Merciful12** [JSMonk/hegel#200]
I'm not sure i doing it correctly but here it is
```js
type Fn = <T>(value: T) => T

let fn: Fn = (s:string) => '2'
```
[try](https://hegel.js.org/try#C4TwDgpgBAYgdlAvFAPAFQHwAoBuBDAGwFcIAuKNASiQwoCg6CJgoAzOc+JKLAZ1N7AATgEs4Ac2qJaAcgBMMoA)

**Comment by ikabirov** [comment]
it's ok. `<T>(T) => T` is more common type and can receive any value.

**Comment by Merciful12** [comment]
how to fix error then?

**Comment by srg-kostyrko** [comment]
not sure what are you trying to achieve but in this case a better way to describe `Fn` would be

```typescript
type Fn<T> = (value: T) => T

let fn: Fn<string> = (s:string) => '2'
```

**Comment by Merciful12** [comment]
i want like so

```js
type Fn = <T>(value: T) => T

function test(fn: Fn) {...}

test((s: string) => s)
test((s: number) => s)

```

**Comment by srg-kostyrko** [comment]
```typescript
type Fn<T> = (value: T) => T

function test<T>(fn: Fn<T>) {}

test((s: string) => s)
test((s: number) => s)
```

**Comment by Merciful12** [comment]
ok, thanks. Can it recognize automatically without  generic here `function test<T>(fn: Fn<T>)`?

**Comment by srg-kostyrko** [comment]
this is a question for @JSMonk

**Comment by ikabirov** [comment]
@Merciful12 is't incorrect case. Without generic in function `test` you can call function with any parameter:
```js
type Fn = <T>(value: T) => T

function test(fn: Fn) {
  fn(true)
}

test((s: string) => s)
test((s: number) => s)
```
