### ISSUE TITLE
Incorrect Return Type

### ISSUE THREAD

**Issue by leushkin** [JSMonk/hegel#204]
https://hegel.js.org/try#C4TwDgpgBAcghsKBeKBGKAfKAmAULgMwFcA7AY2AEsB7EqYCAZ2AAoA3OAGwC5YEBKKAG8oAelFQA7gCdaAc3rgIuKKqiNJlYGQAW7LoKEq1JsnEbRUvaRGBFpdAOSpHxk6rMWc12-afZXdzUAEwgCOCJOYB87ByhHQLUAX1wkoA

I think I understand why is this bug happen. At `call.js` file, `isFinal` variable checks whether creator block or not, it works fine for if statement, but not for switch, because its creator is `undefined` for some reason. I tried to change `.every(parent => parent.creator === "block");` with `.every(parent => parent.type === "block");` , and everything was working as expected, but I broke some tests =(

I can take a look why does creator variable is undefined for switch statement

**Comment by JSMonk** [comment]
Fixed in `0.0.43` release. Thank you for the contribution ^_^.
