### ISSUE TITLE
don't exist "npm run compile" command

### ISSUE THREAD

**Issue by buttercubz** [JSMonk/hegel#210]
https://github.com/JSMonk/hegel/blob/5a0217148d07b0283c966f277be1b0d37cb82c3a/packages/language-server/package.json#L52

I can't compile the extension for vscode using "npm run compile" in "hegel / packages / language-server" directory

**Comment by JSMonk** [comment]
@buttercubz 
Oh, I will add it soon.
Thank you for the issue ^_^.

**Comment by YevhenKap** [comment]
@buttercubz, you may try extension in debug mode.
```bash
git clone https://github.com/JSMonk/hegel.git
cd hegel/packages/language-server
code .
```
Then click `Debug` option and start. `VSCode extension host` will be opened and you can try extension.

**Comment by buttercubz** [comment]
thanks 👍

**Comment by YevhenKap** [comment]
`language-server` needs documentation and extension needs many improvements, so there will be lot of works)

**Comment by JSMonk** [comment]
I've just changed info about running the extension.
Currently, `vsce` tool, which is needed to package the extension, have a problem with different `npm` version. [Issue 246](https://github.com/Microsoft/vscode-vsce/issues/246)
So, it will be a lot of problem with local building the extension.
Please, try to run it by VS Code debugger by the [Instruction](https://hegel.js.org/docs/editor-plugins#visual-studio-code) 
Thank you for your interest.
And thank you a lot for the issue ^_^.
