### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by karimsa** [JSMonk/hegel#213]
Hegel core errors out when you call a method on an ambiguously typed object and pass it a function, even if that function is strongly typed.

Example: https://hegel.js.org/try#GYVwdgxgLglg9mABMAFAQwJSIN4ChEGIBOAplCEUmgHQBGANmgBYooQBciAzlETGAHMsAXgB8iCBlwBfXEA

I would expect that the type of `f` is `({ blah: ((string) => string) => _b }) => _b`.

---

One thing to note is that Hegel seems to only output the error's message when something goes wrong. It would be nice to have some context for when errors occur, even if the error is unexpected. For instance, the filename, line, and column would be nice. I had to hook up node's inspector to the process and dig into the AST to find the location of this error.

**Comment by JSMonk** [comment]
Oh. It's a problem. We will fix it soon.
Thank you a lot for the issue ^_^.

**Comment by karimsa** [comment]
Looks like this is working now!

**Comment by thecotne** [comment]
@karimsa yes. after this #252 and this #256 hegel playground is running on master (it was last published version before if i am not mistaken)

so it works on playground but not on latest published version...

**Comment by JSMonk** [comment]
Fixed in 0.0.44
