### ISSUE TITLE
typescript non-goal is *provably correct* not *probably correct*

### ISSUE THREAD

**Issue by jamesmanning** [JSMonk/hegel#214]
From the Hegel page https://hegel.js.org/docs#benefits-and-disadvantages-over-typescript

> One of the non-goals of TypeScript is: "Apply a sound or "**probably** correct" type system. Instead, strike a balance between correctness and productivity."

The actual non-goal

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

> Apply a sound or "**provably** correct" type system. Instead, strike a balance between correctness and productivity.

Kind of odd since it looks like a copy-paste otherwise - maybe some kind of autocorrect got involved.

**Comment by JSMonk** [comment]
Thank you a lot ^_^
I will change it soon.

**Comment by thecotne** [comment]
copy past quote was updated in this commit https://github.com/JSMonk/hegel/commit/620b135469bd28c4ae6420333fd951206c42487d#diff-348867911e6a15bef82fdd2a4ef49f79
