### ISSUE TITLE
Function should return something with type "true"

### ISSUE THREAD

**Issue by thecotne** [JSMonk/hegel#222]
```ts
class User { }

function giveMeUser(user: User): true {
  if (user instanceof User) {
    return true
  }

  return true
}
```

[try](https://hegel.js.org/try#MYGwhgzhAECqEFMBO0De0C+AoLAzArgHbAAuAlgPaHQDmZAbggLILzIAU+iSAXHNwEo+JJPgRos0aGVzRO3aYQgkwxBBVlskAiVKlIEJfEmoixkzDn2Hjp0QiwYgA)

**Comment by JSMonk** [comment]
Fixed in 0.0.44
