### ISSUE TITLE
Can't install VSCode extenstion

### ISSUE THREAD

**Issue by snatvb** [JSMonk/hegel#228]
Hello. On your [site](https://hegel.js.org/docs/editor-plugins#visual-studio-code), link must lead to marketplace but it is not. Link is leading to home page of the site.

Ok, I tried install manually, but I can't. Command `npm run compile` does not exist in package.json of `hegel/packages/language-server`, because I can't compile extention and install in my IDE.

I want to try your solution.

**Comment by JSMonk** [comment]
I've just changed info about running the extension.
Currently, `vsce` tool, which is needed to package the extension, have a problem with different `npm` version. [Issue 246](https://github.com/Microsoft/vscode-vsce/issues/246)
So, it will be a lot of problem with local building the extension.
Please, try to run it by VS Code debugger by the [Instruction](https://hegel.js.org/docs/editor-plugins#visual-studio-code) 
Thank you for your interest.
And thank you a lot for the issue ^_^.

**Comment by snatvb** [comment]
![image](https://user-images.githubusercontent.com/1572963/82754347-feb31c00-9dd4-11ea-9b1b-f4e4ee6e0fb3.png)
In debug I got this error and after nothing working

**Comment by YevhenKap** [comment]
@snatvb did you make `npm install` or `yarn`(from yesterday we moved to yarn)?

**Comment by thecotne** [comment]
apparently i broke it in #252 

now i am trying to fix it and i got it in a state where it does not report any errors but still does not work : /

**Comment by YevhenKap** [comment]
@thecotne no. It is not your fault. There is problem to package extension with `npm`. We need `yarn`. You did great work)

**Comment by thecotne** [comment]
it was failing to start for me because of change in file structure of `@hegel/core` 

this is my fix but it still does not exactly work https://github.com/JSMonk/hegel/pull/260/files#diff-d73f388b124308df3ed9c8993f08f40bL1-R3

**Comment by YevhenKap** [comment]
@thecotne yeah. It will not work until new change will be in npm registry. `language-server` use `@hegel/core` and `@hegel/cli` from `npm`, not local ones. :(

**Comment by thecotne** [comment]
@YevhenKap no after yarn it uses local packages (except `@hegel/typings` as it's broken)

well it should use local packages if it's configured correctly

**Comment by snatvb** [comment]
@YevhenKap oh, probably you are right, i will look at that soon

**Comment by snatvb** [comment]
Yes, it's work! 
But has some problems
![image](https://user-images.githubusercontent.com/1572963/83336280-c6bb4580-a2ba-11ea-8c04-a5d0c124c488.png)

**Comment by thecotne** [comment]
@snatvb syntax highlighting is not provided by extension ...

is this vscode with javascript syntax? maybe you have some other extension messing with js syntax?

**Comment by snatvb** [comment]
@thecotne  maybe problem in theme, i think this problem with <T> and second <T>
by the way, why hegel does not suppord `number[]` syntax?
