### ISSUE TITLE
How to compile to JavaScript?

### ISSUE THREAD

**Issue by devhammed** [JSMonk/hegel#240]
There are only two supported commands in Hegel CLI and compiling to JavaScript is not one of them.

**Comment by Raynos** [comment]
There are instructions on the website.

https://hegel.js.org/docs/install#setup-project

Probably useful to add these to the readme in GitHub too

**Comment by JSMonk** [comment]
Now, you can see the instruction in [`README.md` "Installing" section](https://github.com/JSMonk/hegel#installing). (**Step 4**).
Thank you for the question and advice ^_^.

**Comment by devhammed** [comment]
Thank you 💯💯💯
