### ISSUE TITLE
user defined generic with magic type

### ISSUE THREAD

**Issue by thecotne** [JSMonk/hegel#269]
this is ok

```ts
const arr02: Array<$Values<[1, 2, 3]>> = [];
```

[try](https://hegel.js.org/try#MYewdgzgLgBAhgJwQBgEwC4YEElwJ4A8AJAGpwA2ArgKYQEDaAjADQyqsDMAugHw8wBeGPS4BuAFBA)

this is "AnalyzationError: Cannot read property 'argumentsTypes' of undefined"

```ts
type Values<T> = Array<$Values<T>>;

const arr01: Values<[1, 2, 3]> = [];
```

[try](https://hegel.js.org/try#C4TwDgpgBAaghgGwK4QM4B4AqA+KBeKAQQCdi4R0ASeZNLbbAbgChmBjAewDtVgo5SABgCMALliIUGANrCANFABMCgMwBdXAWlqWQA)

**Comment by JSMonk** [comment]
Fixed in 0.0.44
