### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by antonkatz** [JSMonk/hegel#287]
Hello,

Just tried to install `hegel`
Tried to install it globally with npm first, and got the error in the title
Then tried a local install with yarn, and got the same error

Ran `hegel init` just fine and it created a config file.

What am I doing wrong?

**Comment by antonkatz** [comment]
So, in the config I excluded some directories, and it started working.
Not sure what exactly the issue was, or which directory it hit.

Maybe include a directory path if this error occurs for easier debugging?

**Comment by JSMonk** [comment]
Hmmm. Could you give some information about the project or directory in the project?

**Comment by antonkatz** [comment]
I think I know what happened there. Now that I went to take a look at my config again (it changed) and my folder structure (it changed as well) I think that the issue was a nested `node_modules` folder that didn't get filtered out by `- ./node_modules/**`. I'm going to close this issue. Might be useful to someone as oblivious as me.
