### ISSUE TITLE
Question: Why not yarn or pnpm?

### ISSUE THREAD

**Issue by scink** [JSMonk/hegel#4]
As far as i know yarn workspaces make work with lerna much more convenient

**Comment by raveclassic** [comment]
There're a lot of options, for example [cycle.js](https://cycle.js.org/) [uses](https://github.com/cyclejs/cyclejs/issues/818) [pnpm](https://github.com/pnpm/pnpm) :)

**Comment by scink** [comment]
@raveclassic, description in the linked issue sounds really good

**Comment by JSMonk** [comment]
Because npm is an standard and the most stable and long term supported package manager.
