### ISSUE TITLE
Состояние анализатора

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [JSMonk/hegel#6]
Всем привет, заинтересовался вашим анализатором после просмотра доклада, спасибо что решили поделиться. 
Решил подождать некоторое время, но сейчас захотелось попробовать его в живую. 
В каком сейчас состоянии анализатор, можно ли его использовать уже в дикой среде? 
Есть краткое руководство как его установить и запустить? (для тех кто не имел дело ранее с language-server).

**Comment by JSMonk** [comment]
Доброе время. Извините за столь долгую задержку ответа.
Сейчас анализатор в состоянии преальфы и доступен пока только в виде development сборки.
У меня есть надежда, что альфа будет выпущена в этом месяце, но, видимо, я не успею все сделать, что хотелось, поэтому она будет доступна в следующем месяце.
Тогда же будет сделано руководство по запуску.
P.S. Сделал issue на руководство :)
Спасибо, что интересуетесь, это для меня действительно важно.
