### ISSUE TITLE
CLI does not analyse project

### ISSUE THREAD

**Issue by YevhenKap** [JSMonk/hegel#64]
I have installed `@hegel/cli` globally first and then locally in project. But when I type `hegel` command output is like this below:

```sh
$ hegel
Path "events" cannot be resolved
```

What can it be?
P.S.: I install CLI with npm. Node version is 13.12.0

**Comment by JSMonk** [comment]
Yes. It seems like we don't provide typing for "events" Node.js models. We will add it soon.
Thank you for your contribution ^_^.

**Comment by JSMonk** [comment]
"events" module has been added to the typing, so, if you will have an error - please create a new issue. Thank you for the contribution ^_^
