### ISSUE TITLE
Number is incopatible with type "0" from example

### ISSUE THREAD

**Issue by sergeysova** [JSMonk/hegel#66]
```ts
function sum(...numbers: Array<number>) {
  return numbers.reduce((a, b) => a + b, 0); // Error here
}

sum();             // 👌!
sum(1);            // 👌!
sum(1, 2);         // 👌!
sum(1, 2, 42);     // 👌!
sum(1, 2, 42, 14); // 👌!
// ...
```

```
Type "number" is incompatible with type "0"
```

[Playground](https://jsmonk.github.io/hegel/try#GYVwdgxgLglg9mABAZxAWwBQDodnQIwFMAnZALkQEFjiBDATwB480jiA+ASkQG8AoRImKEoIYkhZtkWYQBMQEQhgy0ANInzcAvO0S1EAag3qADJwDcfAL58+qTBcFPnzgPSvEgXg3AMjsBCO+gYAIyOLmHuXn4BmEHqAEyhYYgRPv72wfHqACwJ5i4pUemxiHHZpYhBWY4F-hE4WHxAA)

Example from [Rest Argument](https://jsmonk.github.io/hegel/docs/function-types#rest-argument)

**Comment by thecotne** [comment]
very interesting bug! 

problem is that number literal `0` is assumed to be `U` in `reduce` (wrong) 

and then number literal is not assignable to number (this part is correct)

so if you annotate `U` as number anywhere it will work

```js
void [1].reduce((a, b) => a + b, 0); // Error

void [1].reduce<number>((a, b) => a + b, 0); // Ok
void [1].reduce((a: number, b) => a + b, 0); // Ok
void [1].reduce((a, b): number => a + b, 0); // Ok

const num: number = 0// use type casting in variable declaration since inline type casting is not supported

void [1].reduce((a, b) => a + b, num); // Ok
```

this is type definition of reduce

```ts
interface Array<T> {
  // ...
  
  reduce<U>(
    callbackfn: (
      previousValue: U,
      currentValue: T,
      currentIndex: number,
      array: T[]
    ) => U,
    initialValue?: U
  ): U;
  
  // ...
}
```

[packages/typings/standard/index.d.ts#L286-L294](https://github.com/JSMonk/hegel/blob/master/packages/typings/standard/index.d.ts#L286-L294)

possible solution would be to try super type of inferred type if original inferred type does not work (walking up to the chain until reaching root type or finding something that works)

**Comment by JSMonk** [comment]
@thecotne, Yes, the problem is in the type inference and unification algorithm. I'm thinking about the solution.
