### ISSUE TITLE
No .fill method on Array

### ISSUE THREAD

**Issue by sergeysova** [JSMonk/hegel#68]
```ts
const numbers: Array<number> = [];

numbers.fill(500); // Error here
```

```
Property "fill" does not exist in "Array<number>"
```

[Playground](https://jsmonk.github.io/hegel/try#MYewdgzgLgBGCuBbARgUwE4QFwwILvQEMBPAHgRQwD4YBeGAbQF0BuAKDYrUwDoAzAJYAbIQAoArAAZJAShZA)

**Comment by JSMonk** [comment]
Thank you fro contribution ^_^
