### ISSUE TITLE
Type "$PropertyType<_a, _b>" is incompatible with type "_c"

### ISSUE THREAD

**Issue by sergeysova** [JSMonk/hegel#70]
```ts
// Type of "prop" function is "<_a: Object, _b: $Keys<_a>>(_a, _b) => $PropertyType<_a, _b>"
function prop(a, b) {
    return a[b]; // Error here
}
```

```
Type "$PropertyType<_a, _b>" is incompatible with type "_c"
```

[Playground](https://jsmonk.github.io/hegel/try#PTAEBUE8AcFNQPYDNQCJoCcHVaJBXAOwGMAXASwUNHIGc0AeAfQEMAuUAeQCMArWMgBpQTbhwAkAaViRazFgD4FAClbDRASlABeBaHEAFLHAylIUOPPXcFqAFAESFKqEzZlLYdy0BvO6ADQDFhSfAxqFgBtbgBdAG47AF8gA)

This is from an example at [Arguments](https://jsmonk.github.io/hegel/docs/type-inference#arguments)

**Comment by mikhailKilin** [comment]
Another improvement for $PropertyType:
`type AA = {
  a: string;
  b: number;
}
type AAA = 'a' | 'b';

type AAAA = $PropertyType<AA, AAA> //error, but should infer string | number`

**Comment by JSMonk** [comment]
It seems like after going to the lazy application we broke an $PropertyType. We will fix it soon. Thank you for your contribution ^_^.
