### ISSUE TITLE
Properties in function arguments should be invariant

### ISSUE THREAD

**Issue by vkurchatkin** [JSMonk/hegel#74]
Small example:

```js
const a: { a: number} = { a: 1 };
const b: {a : number | string } = a; // CORRECT, not allowed


function foo(obj: { a : number | string }) {}
const f: ({ a: number}) => undefined = foo; // INCORRECT, allowed
```

**Comment by JSMonk** [comment]
1. If you will use cast between link type it will be incorrect behavior, because the initial value can be changed. https://jsmonk.github.io/hegel/docs/array-types#subtyping
2. The. the function is ok, because of in foo function will be provided only number;

**Comment by JSMonk** [comment]
Thank you for contribution ^_^

**Comment by vkurchatkin** [comment]
No, it's not ok. Here is a simple example of a runtime error:

```js
function foo(obj: { a : number | string }) {
    obj.a = 'foo';
}

const f: ({ a: number}) => undefined = foo; 

const obj = { a: 1 };

f(obj);

obj.a.toFixed(); // BOOM
```

**Comment by JSMonk** [comment]
Hmmm, really. I Will fixed it soon. 
Thank you a lot for your contribution ^_^
