### ISSUE TITLE
Interface without ; throw Unexpected token

### ISSUE THREAD

**Issue by polemius** [JSMonk/hegel#79]
I'm not sure maybe it is should be in this way but in TypeScript no errors:

```
interface B {
    a: number
    b: bool
}
```
<img width="305" alt="Screen Shot 2020-04-11 at 23 04 16" src="https://user-images.githubusercontent.com/48512663/79054895-14b3b580-7c49-11ea-8a73-4fcdf088b72b.png">

**Comment by JSMonk** [comment]
It looks like you missed `;` (semicolon)

**Comment by polemius** [comment]
Yeah, I know that there should be a semicolon but in TypeScript I have no errors with this code.

**Comment by JSMonk** [comment]
In Flow.js syntax it unresolved syntax.

**Comment by polemius** [comment]
Ok. I see. Thanks 🙂
