### ISSUE TITLE
Array.isArray returns type unknown instead of boolean

### ISSUE THREAD

**Issue by digis-romanchenkopv** [JSMonk/hegel#80]
https://github.com/JSMonk/hegel/blob/8160a4c2b0acc4c070bfa836943427fd1780f153/packages/typings/standard/index.d.ts#L5014

Playground reference: https://jsmonk.github.io/hegel/try#MYewdgzgLgBAhgLhgIxCANgUzmGBeGAQQCdi4BPAOgEsISzyAKAbQBYBdASgG4AoIA

**Comment by JSMonk** [comment]
Yes. It seems like Hegel doesn't parse TypeScript Type Guards as boolean return type. We will fix it soon.
