### ISSUE TITLE
Super Code Optimisation

### ISSUE THREAD

**Issue by sirinath** [JSMonk/hegel#83]
Is it possible to have code optimisations like in [Prepack](https://prepack.io/) and [Closure Compiler](https://developers.google.com/closure/compiler/). 

In the case of DOM manipulations and JS generated CSS without continuous animations and update, generate the final rendering.

**Comment by JSMonk** [comment]
Sorry, but it's not a goal of the Hegel project. At this moment, we try to implement a strong type system with high-level type inference. As you can see, Hegel doesn't contain a build step, it's an only analyzation tool and build-step we delegate to babel or to `flow-remove-types` utility (https://jsmonk.github.io/hegel/docs/install#setup-project).
Thank you for your question ^_^.
